server:
  port: 8020
  servlet:
    context-path: /core
    
spring:
  application:
    name: core-management
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: spring-cloud-config
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/