server:
  port: 8030

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
      
    
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
#          uri: https://gitee.com/chuyaliang/config-center.git
#          search-paths: ovopark-config
#          username: 444782834@qq.com
#          password: 65325646
